<?php

namespace synry63\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ColorThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColorThemeRepository extends EntityRepository
{
}