<?php

namespace synry63\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ThemeUtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeUtilisateurRepository extends EntityRepository
{
    public function test(){
      //  $dql = "SELECT z,t FROM synry63BlogBundle:ThemeUtilisateur z JOIN z.theme t WHERE z.user = 1";
      // $dql = "SELECT t FROM synry63BlogBundle:Theme t LEFT JOIN synry63BlogBundle:ThemeUtilisateur tu ";
      $qb = $this->createQueryBuilder('tu')
               ->leftJoin('tu.theme', 't')
               ->addSelect('t');
         $test =    $qb->getQuery()
                    ->getResult();
      //  $query = $this->_em->createQuery($dql);
        
       // return  $query->getResult();
    }
    public function test2(){
       $dql = "SELECT z FROM synry63BlogBundle:ThemeUtilisateur z WHERE z.user_id";
        $query = $this->_em->createQuery($dql);
        
        return  $query->getResult();
    }
    public function getNbThemeUser($id){
        $dql = "SELECT COUNT (tu) FROM synry63BlogBundle:ThemeUtilisateur tu WHERE tu.user=:id";
        $query = $this->_em->createQuery($dql);
        $query->setParameter('id',$id);
        $r =  $query->getResult();
        $rr = $r[0][1];
        return $rr; 
    }
    
}